version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: sonjumoney-container
    restart: always
    ports:
      - "3307:3306" # 컨테이너의 MySQL 기본 포트를 3307로 매핑
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sonjudb
      MYSQL_USER: sonju
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
